spring:
  application:
    name: BoardProject

  output:
    ansi:
      enabled: always

  messages:
    fallback-to-system-locale: false

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create