spring:
  application:
    name: BoardProject

  output:
    ansi:
      enabled: always

  profiles:
    active: local

  messages:
    fallback-to-system-locale: false

  datasource:
    url: jdbc:h2:mem:boarddb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create